### PR TITLE
checking for SCSS before adding root selector

### LINKED ISSUE #39: Don't add `:root` selector to `*.module.scss` either
Due to only checking for `*.module.css` extension, we get the following error when using SCSS Modules:

```
./components/Layout/Main.module.scss:1:1
Syntax error: Selector ":root" is not pure (pure selectors must contain at least one local class or id)
```

**Code:**

https://github.com/limitlessloop/flex-gap-polyfill/blob/8d3f3607dfedeefc37e76fc6053d03cb53b510e5/src/index.js#L150-L151

I've got a pull-request coming!

### PR DESCRIPTION
**Pull request by nemoDreamer**
Fixes #39

### CODE REVIEW

**Comment by nemoDreamer** [comment]
@limitlessloop I've fixed the build, but can't fix the AppVeyor fail without updating dependencies, which I don't think should go in this PR...:

```
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--ignore-scripts"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code EPEERINVALID
npm ERR! peerinvalid The package rollup@2.48.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer rollup-plugin-babel@4.3.3 wants rollup@>=0.60.0 <2
npm ERR! peerinvalid Peer @rollup/plugin-commonjs@18.1.0 wants rollup@^2.30.0
```

**Comment by limitlessloop** [comment]
No worries. Thanks very much for your contribution! I'll sort the issue out with AppVeyor.

**Comment by limitlessloop** [comment]
I also added legacy `.sass` extension and the PostCSS `.pcss` extension. Thanks again!

**Comment by nemoDreamer** [comment]
Oh sweet, great catch!

**Pull request merged**
